// import './js/variable.js';
// import'./js/module2-1.js';
// import'./js/module2-2.js';
// import './js/tostring.js';
// import './js/homework1.js';
// import './js/homework2.js';
// import './js/module3-1.js';
// import  './js/homework3.js';
// import './js/module3-2.js';
import './js/homework4.js';